dist: bionic

branches:
  except:
    - /^dependabot\/.*$/

jobs:
  include:
    - &test
      stage: test

      language: python
      python: 2.7

      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - python-dev

      install:
        - pip install -r requirements.txt

      before_script:
        - git submodule update --init --recursive

      script:
        # Try to install the package
        - pip install .

        # Run tests
        - pytest -vv

    - <<: *test
      python: 3.6

    - stage: test
      name: "Linting (black)"

      language: python
      python: 3.6

      install:
        - pip install black==18.9b0

      script:
        - black tests *.py --check

notifications:
  email:
    on_failure: change

deploy:
  provider: pypi
  distributions: "sdist"
  skip_cleanup: true
  user: Tobias.Bieniek
  password:
    secure: EoZBUYwOumozqjqZ0ODDUfywSF+kSxUeIEVQNzjKjWdbzdwzD9tBi3uEGed6+CkZr9R/5arc/YAjCt/1zuKfdgOD6Mh6VxgkcPoaBkfF0nsTKwgNzN29BEU4P1V7nWpILy7JPC80K0fCvH2UwGlmB79oMFuLu74vcf2MhTKA40E=
  on:
    tags: true
    repo: skylines-project/py-xcsoar
